export const ADD_NEW_MAP = 'ADD_NEW_MAP';
export const UPDATE_TIME = 'UPDATE_TIME';
export const CHANGE_DEFAULT_SETTING = 'CHANGE_DEFAULT_SETTING';
export const SET_TO_DEFAULT = 'SET_TO_DEFAULT';
export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';